name: Release

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

env:
  GO_VERSION: '1.23'

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  release-please:
    name: Release Please
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
      sha: ${{ steps.release.outputs.sha }}
      upload_url: ${{ steps.release.outputs.upload_url }}
    
    steps:
      - name: Run Release Please
        id: release
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: go
          package-name: bedrock-forge
          changelog-sections: |
            [
              {"type":"feat","section":"Features"},
              {"type":"fix","section":"Bug Fixes"},
              {"type":"docs","section":"Documentation"},
              {"type":"deps","section":"Dependencies"},
              {"type":"refactor","section":"Code Refactoring"},
              {"type":"test","section":"Tests"},
              {"type":"build","section":"Build System"},
              {"type":"ci","section":"Continuous Integration"}
            ]

  build-and-upload:
    name: Build and Upload Release Assets
    runs-on: ubuntu-latest
    needs: release-please
    if: needs.release-please.outputs.release_created == 'true'
    
    strategy:
      matrix:
        include:
          - os: linux
            arch: amd64
            runner: ubuntu-latest
          - os: linux
            arch: arm64
            runner: ubuntu-latest
          - os: darwin
            arch: amd64
            runner: ubuntu-latest
          - os: darwin
            arch: arm64
            runner: ubuntu-latest
          - os: windows
            arch: amd64
            runner: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.release-please.outputs.sha }}

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Build binary
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
          CGO_ENABLED: 0
        run: |
          # Set binary name
          binary_name="bedrock-forge"
          if [ "${{ matrix.os }}" = "windows" ]; then
            binary_name="bedrock-forge.exe"
          fi
          
          # Build with version info
          go build -ldflags "-s -w -X main.version=${{ needs.release-please.outputs.tag_name }} -X main.commit=${{ needs.release-please.outputs.sha }}" \
            -o "${binary_name}" \
            ./cmd/bedrock-forge
          
          # Create archive
          archive_name="bedrock-forge-${{ needs.release-please.outputs.tag_name }}-${{ matrix.os }}-${{ matrix.arch }}"
          
          if [ "${{ matrix.os }}" = "windows" ]; then
            zip "${archive_name}.zip" "${binary_name}" README.md LICENSE
            echo "ASSET_PATH=${archive_name}.zip" >> $GITHUB_ENV
            echo "ASSET_NAME=${archive_name}.zip" >> $GITHUB_ENV
          else
            tar -czf "${archive_name}.tar.gz" "${binary_name}" README.md LICENSE
            echo "ASSET_PATH=${archive_name}.tar.gz" >> $GITHUB_ENV
            echo "ASSET_NAME=${archive_name}.tar.gz" >> $GITHUB_ENV
          fi

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release-please.outputs.upload_url }}
          asset_path: ${{ env.ASSET_PATH }}
          asset_name: ${{ env.ASSET_NAME }}
          asset_content_type: application/octet-stream


  update-homebrew:
    name: Update Homebrew Formula
    runs-on: ubuntu-latest
    needs: [release-please, build-and-upload]
    if: needs.release-please.outputs.release_created == 'true'
    
    steps:
      - name: Update Homebrew formula
        uses: dawidd6/action-homebrew-bump-formula@v3
        with:
          token: ${{ secrets.HOMEBREW_GITHUB_TOKEN }}
          formula: bedrock-forge
          tag: ${{ needs.release-please.outputs.tag_name }}
          revision: ${{ needs.release-please.outputs.sha }}
        continue-on-error: true  # Don't fail the release if Homebrew update fails

  notify-release:
    name: Notify Release
    runs-on: ubuntu-latest
    needs: [release-please, build-and-upload]
    if: needs.release-please.outputs.release_created == 'true'
    
    steps:
      - name: Create release summary
        run: |
          echo "## 🎉 Bedrock Forge ${{ needs.release-please.outputs.tag_name }} Released!" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### 📦 Installation" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Go Install (Recommended):**" >> $GITHUB_STEP_SUMMARY
          echo '```bash' >> $GITHUB_STEP_SUMMARY
          echo "go install github.com/chandra447/bedrock-forge/cmd/bedrock-forge@${{ needs.release-please.outputs.tag_name }}" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Download Binaries:**" >> $GITHUB_STEP_SUMMARY
          echo "- [Linux AMD64](https://github.com/${{ github.repository }}/releases/download/${{ needs.release-please.outputs.tag_name }}/bedrock-forge-${{ needs.release-please.outputs.tag_name }}-linux-amd64.tar.gz)" >> $GITHUB_STEP_SUMMARY
          echo "- [Linux ARM64](https://github.com/${{ github.repository }}/releases/download/${{ needs.release-please.outputs.tag_name }}/bedrock-forge-${{ needs.release-please.outputs.tag_name }}-linux-arm64.tar.gz)" >> $GITHUB_STEP_SUMMARY
          echo "- [macOS AMD64](https://github.com/${{ github.repository }}/releases/download/${{ needs.release-please.outputs.tag_name }}/bedrock-forge-${{ needs.release-please.outputs.tag_name }}-darwin-amd64.tar.gz)" >> $GITHUB_STEP_SUMMARY
          echo "- [macOS ARM64](https://github.com/${{ github.repository }}/releases/download/${{ needs.release-please.outputs.tag_name }}/bedrock-forge-${{ needs.release-please.outputs.tag_name }}-darwin-arm64.tar.gz)" >> $GITHUB_STEP_SUMMARY
          echo "- [Windows AMD64](https://github.com/${{ github.repository }}/releases/download/${{ needs.release-please.outputs.tag_name }}/bedrock-forge-${{ needs.release-please.outputs.tag_name }}-windows-amd64.zip)" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### 🔄 GitHub Action" >> $GITHUB_STEP_SUMMARY
          echo '```yaml' >> $GITHUB_STEP_SUMMARY
          echo "- uses: chandra447/bedrock-forge@${{ needs.release-please.outputs.tag_name }}" >> $GITHUB_STEP_SUMMARY
          echo "  with:" >> $GITHUB_STEP_SUMMARY
          echo "    aws_role: \${{ vars.AWS_DEPLOYMENT_ROLE }}" >> $GITHUB_STEP_SUMMARY
          echo "    tf_state_bucket: \${{ vars.TF_STATE_BUCKET }}" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY